Algoritmo "4A.Orientação a Objetos"
// Data atual  : 12/01/2023

tipo
cadastroCliente = registro
nome: caractere
rg: caractere
idade: inteiro
fimregistro

Var
cliente1: cadastroCliente

Inicio

Escreval("Digite seu nome: ")
leia(cliente1.nome)

Escreval("Digite seu rg: ")
leia(cliente1.rg)

Escreval("Digite sua idade: ")
leia(cliente1.idade)

Escreval("Nome: ", cliente1.Nome," - RG: ", cliente1.rg," - Idade: ", cliente1.idade)


Fimalgoritmo